tox-dev/pipdeptree

- pipdeptree.py
- tests/test_pipdeptree.py
Implementation for `--reverse` mode. This is actually an alternate implementation for the first one that was proposed via this PR - https://github.com/naiquevin/pipdeptree/pull/33.
The changes on this branch includes major refactoring of code.
> Reverse mode

- .travis.yml
- setup.py
- tox.ini
> Add Python 3.5 support

- pipdeptree.py
Hi Vineet, I'd like to use pipdeptree with my buildbot builds in order to prevent any dependency issues from sneaking in over time. In order to do this, pipdeptree would have to return non-zero if there are any conflicting/cyclical dependencies to trigger a failure in the build. In order to support that I've added in a -werror flag (similar to gcc), which will return 1 when there's conflicts or cyclical deps, and 0 otherwise. I've preserved the same behavior for -w and --nowarn (to suppress the warnings), but now they cannot both be present at the same time to prevent conflicts like: `pipdeptree -werror --nowarn'. What do you think?
> add -werror to return non-zero when warnings are present

- pipdeptree.py
Extracted from https://github.com/naiquevin/pipdeptree/pull/27
> Extract parser into get_parser function

- CHANGES.md
- pipdeptree.py
- tests/test_pipdeptree.py
This is done for fixing #73. The changes in PR #65 are reverted.
> Release 0.10.1

- README.rst
Supports README pipdeptree version 0.10.1.
> Supports README version 0.10.1

- pipdeptree.py
- tests/test_pipdeptree.py
- tests/virtualenvs/testenv_requirements.txt
This changes adds a flag for producing JSON that is nested the same way as the plain text output.
> Add command line flag `--json-tree` (#86)

- pipdeptree.py
- tests/virtualenvs/pickle_env.py
> Fixed pip import to accomodate refactor in pip 10.0

- .github/workflows/check.yml
- .pre-commit-config.yaml
- LICENSE
- pyproject.toml
- tox.ini
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Generalize license

- .pre-commit-config.yaml
- CHANGES.md
- pyproject.toml
- tox.ini
> Bump tools and deps and fix changelog

- pyproject.toml
Committed via https://github.com/asottile/all-repos
> Bump deps and tools

- src/pipdeptree/__init__.py
- tests/test_pipdeptree.py
- whitelist.txt
Take 2 at addressing #207. Yes, closing #208 was silly without access to reopen PRs... :facepalm:
> Handle and test mermaid output for a reversed tree

- README.md
- src/pipdeptree/__init__.py
- tests/test_pipdeptree.py
- tox.ini
see proposal in #213 for details
> Implement: Use fnmatch for include and exclude #213

- src/pipdeptree/__init__.py
thanks for sharing this software :)
> Fix typo: "Maermaid"

- .github/workflows/check.yml
- tests/test_pipdeptree.py
Committed via https://github.com/asottile/all-repos
> Add 3.12 support

- src/pipdeptree/__init__.py
- tests/test_pipdeptree.py
Resolves #230.
This commit allows dependency trees to be displayed up to a certain depth >= 0. This argument only applies to the default plain-text display. All other display options will ignore this argument.
A few examples using Scrapy:
```console
(venv) ➜  pipdeptree git:(implement-depth-arg) ✗ pipdeptree -p Scrapy -d 1
Scrapy==2.9.0
├── cryptography [required: >=3.4.6, installed: 41.0.1]
├── cssselect [required: >=0.9.1, installed: 1.2.0]
├── itemadapter [required: >=0.1.0, installed: 0.8.0]
├── itemloaders [required: >=1.0.1, installed: 1.1.0]
├── lxml [required: >=4.3.0, installed: 4.9.2]
├── packaging [required: Any, installed: 23.1]
├── parsel [required: >=1.5.0, installed: 1.8.1]
├── protego [required: >=0.1.15, installed: 0.2.1]
├── PyDispatcher [required: >=2.0.5, installed: …
```
> Implement -d/--depth argument

- tests/test_pipdeptree.py
Resolves https://github.com/tox-dev/pipdeptree/issues/244
> Fix test_render_pdf fails on illumos

- src/pipdeptree/__init__.py
- tests/test_pipdeptree.py
> Fix relative venv inspections fails

- .pre-commit-config.yaml
- pyproject.toml
- src/pipdeptree/__init__.py
- tests/guess_version_setuptools.py
- tests/test_pipdeptree.py
- tox.ini
> Add type information

- pyproject.toml
- tests/test_pipdeptree.py
> Fix entrypoints

- src/pipdeptree/_cli.py
- src/pipdeptree/_render/__init__.py
- src/pipdeptree/_render/graphviz.py
- src/pipdeptree/_render/json.py
- src/pipdeptree/_render/json_tree.py
- tests/render/test_graphviz.py
> Improve CLI

- .github/workflows/check.yml
- src/pipdeptree/_discovery.py
- src/pipdeptree/_render/__init__.py
- src/pipdeptree/_render/mermaid.py
- tests/conftest.py
- tests/render/test_mermaid.py
- tests/render/test_text.py
- tests/test_models.py
> Add type check to CI and fix errors

- tests/_models/test_dag.py
PackageDAG.from_pkgs() uses DistPackage.project_name, which is a property that tries to get the project name using importlib.metadata. This commit avoids us reaching out to the environment in the offending unit tests.
Resolves #326.
> Mock importlib.metadata usage in PackageDAG.from_pkgs() tests

- .github/workflows/check.yml
- tests/test_non_host.py
> Add pypy to CI

- .github/ISSUE_TEMPLATE/0-new-issue.yml
- .github/workflows/check.yml
- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
> Declare 3.13 support
