Makefile
pipdeptree.py
tests/test_pipdeptree.py
tests/virtualenvs/.gitignore
tests/virtualenvs/Makefile
tests/virtualenvs/unsatisfiedenv_requirements.txt

I took a crack at #20 (using pkg_resources.parse_version to warn about unsatisfied or missing dependencies). It works pretty well on all the virtualenvs I have on my machine. 
One area that I think can be improved is where I build req_version_str via interpolation ([L307](https://github.com/naiquevin/pipdeptree/compare/master...t0m:master#diff-c9a0cc375d0f079d6251af1de64f535bR307)) so I can pass something like "pipdeptree>=0.1.2" into Requirement.parse. There must be a better way to get that string. Any suggestions?

Show warning for unsatisfied/missing dependencies

---

pipdeptree.py

I have noticed only the base dependency requirement is being currently shown, whereas the full dependency specs are needed for this tool to be useful. Please notice requirements of pbr and SQLAlchemy below:
cristian@cristian:~/projects/pipdeptree$ pipdeptree -w -p sqlalchemy-migrate
sqlalchemy-migrate==0.10.0
- pbr [required: >=1.3,<2.0, installed: 1.8.1]
- six [required: >=1.7.0, installed: 1.10.0]
- SQLAlchemy [required: >=0.7.8,!=0.9.5, installed: 1.0.11]
- sqlparse [installed: 0.1.18]
- decorator [installed: 4.0.6]
- Tempita [required: >=0.4, installed: 0.5.2]
(We should also check if these dependency requirements are being currently satisfied, or if they don't conflict with those of different packages, but this will be addressed by a separate commit.)
Some minor PEP8 violations have …

show full dependency requirements

---

pipdeptree.py
setup.py

As of 6.0.0 pip will default to excluding the usual things we were
hardcoding here, so this just lets pip do its thing naturally.
This also removes 'pipdeptree' from the exclusion list, which seems
mandatory if your application actually *uses* pipdeptree and it's not
just for manual invocation (i.e.humans typing on keyboards)

Defer to pip's list of excluded default packages.

---

README.rst
pipdeptree.py
setup.py

Add the option to output a dependency graph in any output format
supported by GraphViz.
Based on the idea and code from @johnyf to output the dependency
graph as dot code: #43
Goes a step further than that, by using `graphviz` instead of
`networkx` and `pydotplus`, which allows output as dot code as well, but
enables output in any of GraphViz supported output formats directly,
if the GraphViz command line tools are installed.

Add different output options for dependency graph

---

README.rst
pipdeptree.py

An external call to [GraphViz `dot`](http://www.graphviz.org) is still needed, following the approach with `json`. This works even when `dot` is not installed.
An alternative would be to call the `pydot` graph method `write_pdf`, but then all layout options (including output file format) would have to be forwarded to it. Such a design would be nested, unlike the flat approach selected. It could still be added, as a `--pdf` option, or something similar.
This enhancement requires `networkx` and `pydot` (or `pydotplus`, for newer `networkx` versions).
Considering the graph layout option as optional, I did not modify the dependencies listed in `install_requires`. Both of the dependencies are pure Python, so adding them wouldn't make installation more difficult.

ENH: dump dependency graph as graphviz dot code

---

README.rst

Remove --nowarn from examples

---

pipdeptree.py
tests/test_pipdeptree.py

This PR always force pre-filtering of the dependency tree before any rendering of any sort occurs, thus allowing usage `--packages` and `--all` parameters for both JSON or Graphviz output.

Pre-filter Dependency Tree before Rendering

---

tests/virtualenvs/testenv_requirements.txt

psycopg 2.5.2 fails to install with PostgreSQL 10+.

Update psycopg2 version in one of the test environments

---

pipdeptree.py

Fixes #78.
This naive sorted makes the '>' prior to '<', and '!'.

Sorted version spec

---

pipdeptree.py

The package 'pkg_resources' is part of the 'setuptools' project. The
project 'pip' (in its current version) vendors setuptools.
Since 'pipdeptree' currently uses pip's private internal API already,
we might as well use pip's vendored pkg_resources. This, of course,
might break if pip's internals change in a later version.
GitHub: naiquevin/pipdeptree#119

Fix missing 'setuptools' requirement

---

pipdeptree.py
tests/test_pipdeptree.py

In general, folks should have all their dependencies installed for pipdeptree to evaluate everything. However, I was using it to figure out which packages were trying to install a package that was explicitly uninstallable on my platform. This meant that pip failed mid-install, so many remaining packages had not been installed.
This change avoids a crash in the case that a dependency is not installed.
To do: perhaps it should also emit a warning? I suppose silently skipping a check is not the best for users..

Avoid crashing when some dependencies aren't installed

---

.github/workflows/check.yml
dev-requirements.txt
pipdeptree.py
tests/test_pipdeptree.py
tox.ini

This way you can install once (for example via pipx) and reuse it for any existing python environment.
```bash
$ pipdeptree --python venv/bin/python
pip==20.1.1
setuptools==49.2.0
wheel==0.34.2
```
@naiquevin for your attention. The CI fails because I cannot add the virtualenv dependency to Travis, it will only take effect post merge.

Allow querying non-host python intepreters

---

pipdeptree.py

Python converts '\n' to actual newline before putting it into dot format. Although the previous approach somehow works it's better to pass '\n' explicitly.
Generated code before:
```
digraph {
plotly [label="plotly
4.5.4"]
plotly -> six [label=any]
plotly -> retrying [label=">=1.3.3"]
retrying [label="retrying
1.3.3"]
retrying -> six [label=">=1.7.0"]
six [label="six
1.12.0"]
}
```
Generated code after:
```
digraph {
plotly [label="plotly\n4.5.4"]
plotly -> six [label=any]
plotly -> retrying [label=">=1.3.3"]
retrying [label="retrying\n1.3.3"]
retrying -> six [label=">=1.7.0"]
six [label="six\n1.12.0"]
}
```

Shield newline symbol when generating labels for graphviz

---

.github/workflows/check.yml
pipdeptree.py

GitHub upgraded it's `ubuntu-latest` to 20.04, which deprecated python3.4, this patch re-enables python3.4 on ubuntu18.04.
In addition, I slightly refactor the code by adding `Package.__lt__`.
As a result, package sorting can be simplified.

Fix GitHub Actions

---

setup.py

Hi,
Please, add the LICENSE file into metadata dir of your package (e.g. by accepting this pull request).
I understand you probably hate software laws etc., so I will be short.
You are using MIT license. It says also: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." But your whole package distributed on PyPI.org does not contain even one. This short change will add the file LICENSE (with text of MIT license) into metadata of your package (= into e.g. .../site-packages/pipdeptree-2.0.0.dist-info/LICENSE of your virtualenv). This way you are 100% clear and comply with your chosen license.
Thank you for your time.
Pax et bonum.

License file to be included into metadata dir

---

pipdeptree.py

This PR fix the following error:
```
PS D:\Users\Rodrigo\GitHub\deepshift> pipdeptree --graph-output svg > dependencies.svg
Traceback (most recent call last):
File "C:\Python39\Scripts\pipdeptree-script.py", line 33, in <module>
sys.exit(load_entry_point('pipdeptree', 'console_scripts', 'pipdeptree')())
File "d:\users\rodrigo\github\pipdeptree\pipdeptree.py", line 877, in main
output = dump_graphviz(tree,
File "d:\users\rodrigo\github\pipdeptree\pipdeptree.py", line 601, in dump_graphviz
if output_format not in backend.FORMATS:
AttributeError: module 'graphviz.backend' has no attribute 'FORMATS'
```

Fix "AttributeError: module 'graphviz.backend' has no attribute 'FORMATS'"

---

.github/workflows/check.yml
src/pipdeptree/__init__.py

Make pipdeptree works with python 3.11

---

CHANGES.md
pyproject.toml
src/pipdeptree/__init__.py
tests/guess_version_setuptools.py
tests/test_pipdeptree.py

Fixes #162 
The current approach tries to import the package and look at `package.__version__`. This is not exactly reliable and also causes Assertion Error in the case where the packages is `setuptools` (because pipdeptree imports `pip` and `setuptools` can't be imported after `pip` because of weird hacks in setuptools). The better and simpler approach is to use `importlib.metadata.version`.

Use importlib.metadata for guess_version instead of importing the module

---

README.md

Mostly just removing older versions and adding 3.10.
I've removed the comment about 2.6 - support for that ended nearly 9 years ago!
Feel free to edit/tweak as needed.

Update README for tested Python versions

---

src/pipdeptree/__init__.py
tests/test_pipdeptree.py

This is an adhoc re-interpretation of the [`graphviz.dot.Dot.__iter__()` method](https://github.com/xflr6/graphviz/blob/master/graphviz/dot.py#L158-L182) that is used behind the scene by [the original `graph.source` call](https://github.com/tox-dev/pipdeptree/blob/2eb489449169b59711a4fc979f4fc3483e8e81b0/src/pipdeptree/__init__.py#L613-L615) to dump the graphviz dot file content in `pipdeptree` (i.e. when the `--graph-output dot` parameter in called on the CLI).
But in this PR, we forces the sorting of the generated nodes and edge statements of the graph. That way we address issue #188, in which each invokation of the `pipdeptree` generates a different dot file.
The order of the `dot`-statements does not matter because of the nature of dependencies and the way `pipdeptree` process them. …

Make the output of the dot format deterministic and stable

---

src/pipdeptree/__init__.py
tests/test_pipdeptree.py

This PR adds a new `--mermaid` to the CLI to produce Mermaid's Markdown output of the dependency graph.
This closes #129.

Implements Mermaid output

---

src/pipdeptree/__init__.py
tests/test_pipdeptree.py

This PR quotes label strings in the Mermaid produced graph, for both nodes and edges. The way `pipdeptree` currently produce the Mermaid graph is good and working well. This is a safety measure to make sure the output is more resilient.
See the [result in Mermaid's live editor](https://mermaid.live/edit#pako:eNp9kcluwjAURX_FeutgeUhCErWs-IN21boL4yFEzYAyqKWIf-9LCISyqFf2ufe-QT6BaayDDHzZfJm9bnvyulU1wWNK3XVb50lVdF1R56Tr2-bTrazu0NfqY0aii1O_K9BK1ZKGlCn4uNAd0h1SQSXlN2qQGqQR5ezObBHbizm6QYfQIWSUi7sSHrGf2i0sR5Yji2lCZWsWQZPViijYPAs69cPnhuwetIiux1qTZubpl5xkwZOgoZgNdl7karhON4nuQRzTf3N2yaW3geaYX2L8cdj8n9xNk3dLegigcm2lC4v_exqdCvq9q5yCDK_WeT2UvQJVn9Gqh755OdYGsr4dXADDwerebQudt7qCzOuyQ3rQ9VvTVFcTPiE7wTdkgkVUSiHjlLOERUkYB3AcMeXrhKUp53GYcJ6KcwA_UwVGo_MvVqym_A):
For the record, I found out about this more …

Quote Mermaid node and edge labels

---

src/pipdeptree/__init__.py
tests/test_pipdeptree.py

As discussed in Mermaid bug tracker, [some reserved keywords are not allowed as node IDs](https://github.com/mermaid-js/mermaid/issues/4182).
This PR produces unique and non-colliding node IDs in Mermaid output so that graphs are rendered and allowed to reference reserved keywords.

Unique IDs in Mermaid not conflicting with reserved keywords

---

src/pipdeptree/__init__.py
tests/test_pipdeptree.py

Resolves #181.
I followed the layout mentioned in this issue as well as looked at some examples in the anytree project when implementing this.
**Note that** I did have quite a battle trying to align the bullets (e.g. ├──) to be "pointing" to the first character of a dependency name, so I used the power of trial and error to observe if each bullet aligned correctly no matter how far a dependency is down its dependency tree.
I modified the `test_render_text()` to use the Unicode characters to account for my change. I also manually tested this change by looking at projects which have large dependency trees such as Scrapy, TensorFlow, and hatch to see if they will suffer any alignment issues, and from what I was able to see it produced the expected results.
Here is an example using Scrapy: …

Use unicode characters when rendering text

---

tests/test_pipdeptree.py

Resolves #256.
After doing some bisecting and running the testing code using the `randomly` plugin, I found that the problem lies here:
https://github.com/tox-dev/pipdeptree/blob/f18a32136cbc69c13cfdf76c7065e84e25ee4ea8/tests/test_pipdeptree.py#L775
`randomized_dag_copy()` ends up modifying the global variable `t` when it shuffles the list of `ReqPackage`s associated to a `DistPackage`.
This CL fixes this by just shallow copying the list.

Avoid changing `t` in `randomized_dag_copy()` by shallow copying

---

src/pipdeptree/_models.py
src/pipdeptree/_render/mermaid.py
src/pipdeptree/_validate.py
tests/conftest.py

(the previous PR got closed because I accidentally deleted the branch)

Simplify loops

---

pyproject.toml
src/pipdeptree/__main__.py
src/pipdeptree/_cli.py
src/pipdeptree/_render/__init__.py
src/pipdeptree/_render/text.py
tests/render/test_render.py
tests/render/test_text.py
tox.ini

Resolves https://github.com/tox-dev/pipdeptree/issues/269

Fix graphviz CLI failing

---

.pre-commit-config.yaml
src/pipdeptree/_cli.py
tests/render/test_text.py
tests/test_cli.py

Resolves #161.
Had trouble using the `argparse` mutual exclusion API. I couldn't find an approach to get -e to be mutually exclusive to -p and -a without the latter two being mutually exclusive to each other. Therefore, I ended up doing so manually in `get_options()`.

Have --packages and --all work together

---

src/pipdeptree/_validate.py
tests/test_validate.py

Should resolve #191.
The previous implementation of `cyclic_deps()` only detected a dependency cycle when a dependency of a `DistPackage` was dependent on that `DistPackage` (e.g. a -> b -> a). Sadly, this did not bid well when you have a cycle such as a -> b -> c -> d -> e -> a (i.e. it has a depth > 2 with "a" as the root).
This CL reimplements it to use DFS, where we perform DFS on each `DistPackage` and just check to see if this `DistPackage` (think of it as the root node) was revisited (by comparing the current node's key that were are visiting to the root node's key).

Detect dependency cycles beyond a depth = 2

---

src/pipdeptree/_cli.py

Found this while exploring the code. The absence of this field doesn't affect the runtime since the `cast()` call in `get_options()` exists more-or-less to provide information to the type checker.

Add missing `user_only` field in `Options`

---

src/pipdeptree/__main__.py
src/pipdeptree/_models/dag.py
tests/_models/test_dag.py
tests/render/test_text.py

Should resolve #127.
Note that the `include` parameter in `filter_nodes()` was turned into a list so that when printing an error they will appear in order (at the cost of allowing duplicate patterns to be added). I don't see a performance cost by doing this since previously we seem to just iterate `include` rather than do any lookups.
When the -w fail option and the --packages option is given, patterns that fail to match with any package names will printed to stderr and return with exit code 1.
-w suppress and -w silence work as attended.

Exit with error when `-p` given patterns that fail to match

---

.pre-commit-config.yaml
CHANGES.md

it helps to find typos, and in fact, it found one, so fixing it also... :chipmunk:

precommit: enable codespell

---

src/pipdeptree/_models/package.py

This change exists due to how we use ReqPackage. Since we pass a pip._vendor.pkg_resources.Requirement to Package's constructor instead of the expected DistInfoDistribution, using this method and property will cause a crash because Requirement does not have this data.
To resolve this, they have been moved to DistPackage as it makes more sense for the behavior to exist here rather than force ReqPackage to also have this behavior.
**NOTE**: I also believe `version_spec()` should be moved into `ReqPackage` as it doesn't make sense for this to be available to `DistPackage`, but currently we have modules whose logic depend on its return value.

models/package: move `requires()` and `version` to `DistPackage`

---

README.md

Self-explanatory. A new PyPI release should be cut to update the project description on PyPI after this is merged.

Update README to show 2.13.0 CLI syntax

---

src/pipdeptree/_models/package.py
src/pipdeptree/_render/json_tree.py
tests/render/test_json_tree.py

This behavior is specific to `ReqPackage`, so let's just have it exist in this class rather than having it in the `Package` parent class.
Just to be extra careful, I ran the rendering options that may be affected by this change (so graphviz, mermaid, and json tree) in both reversed and non-reversed order to cover the code paths that use `version_spec`. Everything looks fine from what I can see.

models/package: have `version_spec` only exist in `ReqPackage`

---

src/pipdeptree/_models/package.py
tests/_models/test_package.py

Resolves #309 by having the --json render return `"required_version": "Any"` instead of `"required_version": null`.
The only problem with this change is that I'm unsure if this should be considered a breaking change or not...? Not sure if it would be better to just have both --json and --json-tree give null values for this key (I guess it would be easier for users to determine whether or not a required package has a version spec)

Use "Any" value if necessary for required version in JSON render

---

README.md
src/pipdeptree/_cli.py
src/pipdeptree/_models/package.py
src/pipdeptree/_render/__init__.py
src/pipdeptree/_render/text.py
tests/_models/test_package.py
tests/render/test_render.py
tests/render/test_text.py
tests/test_cli.py

Resolves #79.
An example:
```console
$ pipdeptree -d 0 -a --license
chardet==5.2.0 (GNU Lesser General Public License v2 or later (LGPLv2+))
covdefaults==2.3.0 (MIT License)
coverage==7.4.0 (Apache Software License)
diff-cover==8.0.2 (Apache Software License)
distlib==0.3.8 (Python Software Foundation License)
exceptiongroup==1.2.0 (MIT License)
filelock==3.13.1 (The Unlicense (Unlicense))
iniconfig==2.0.0 (MIT License)
Jinja2==3.1.2 (BSD License)
MarkupSafe==2.1.3 (BSD License)
packaging==23.2 (Apache Software License, BSD License)
pip==23.3.2 (MIT License)
pipdeptree==0.1.dev414+g1cd3453 (MIT License)
platformdirs==4.1.0 (MIT License)
pluggy==1.3.0 (MIT License)
pygments==2.17.2 (BSD License)
pytest==7.4.4 (MIT License)
pytest-cov==4.1.0 (MIT License)
pytest-mock==3.12.0 (MIT License) …
```

Implement --license option

---

README.md
src/pipdeptree/_cli.py

Currently, these two options exist alongside global options like --help and --version. However, their behavior closely aligns with the "render" argument group. Therefore, let's just have them in the render group.

Have --license and --reverse options in the "render" argument group

---

src/pipdeptree/_models/package.py
src/pipdeptree/_render/text.py
tests/_models/test_package.py
tests/render/test_text.py

In #318 I did not consider the case where users would pass --reverse along with --license. Currently, doing so would have us output the following:
```console
$ pipdeptree --reverse --license -d 1
chardet==5.2.0
└── diff-cover==8.0.3 [requires: chardet>=3.0.0] (Apache Software License)
coverage==7.4.2
├── covdefaults==2.3.0 [requires: coverage>=6.0.2] (MIT License)
└── pytest-cov==4.1.0 [requires: coverage>=5.2.1] (MIT License)
distlib==0.3.8
└── virtualenv==20.25.1 [requires: distlib>=0.3.7,<1] (MIT License)
exceptiongroup==1.2.0
└── pytest==8.0.1 [requires: exceptiongroup>=1.0.0rc8] (MIT License)
filelock==3.13.1
└── virtualenv==20.25.1 [requires: filelock>=3.12.2,<4] (MIT License)
iniconfig==2.0.0
└── pytest==8.0.1 [requires: iniconfig] (MIT License)
MarkupSafe==2.1.5
└── Jinja2==3.1.3 …
```

Have --license work with --reverse

---

CHANGES.md
src/pipdeptree/_models/dag.py
src/pipdeptree/_models/package.py
tests/_models/test_dag.py
tests/_models/test_package.py

It was found that keys are not pep503 normalized in `pkg_resources`, instead using different regex which retains dots, creating potential mismatch between keys in `Requirement` objects and keys in `DistInfoDistribution` objects.
This change fixes that by applying pep503 normalization on the keys we get from `pkg_resources` objects.
Additionally, it was found that `DistInfoDistribution` uses derived value for `project_name` based on `.dist-info` folder name, which may result in an imprecise package name (not the same as in metadata due to double normalization).
This change recovers true package name from metadata when possible.
Fixes #324

Fix key mismatch between requirements and dists

---

pyproject.toml

We ran the test suite with a decreasing version of pip until it failed at 18.0.
```bash
#!/usr/bin/env bash
pip_version=100  # very high on purpose
install_pip() {
pip_version=$(uv pip install "pip<${pip_version}" 2>&1 | grep -F '+ pip==' | cut -d= -f3)
echo -en "Testing with pip version ${pip_version}: "
}
main() {
echo "Setup"
{
uv venv
. .venv/bin/activate
uv pip install -e .[test,graphviz]
uv pip uninstall pip
} &>/dev/null
install_pip
while :; do
if pytest tests &>/dev/null; then
echo "OK"
install_pip
else
echo "Failed"
break
fi
done
}
main
```
---
The above text is the commit message. Feel free to reword it by squashing the PR.
Output of the script:
```console
% bash testpip.sh
Setup
Testing with pip version 24.0: OK
Testing with pip version 23.3.2: OK
Testing with pip version …
```

List pip as dependency

---

src/pipdeptree/_discovery.py
src/pipdeptree/_models/dag.py
src/pipdeptree/_models/package.py
src/pipdeptree/_util.py
tests/test_discovery.py

Fixes #341.
Using an environment similar to the one shown in the issue:
```console
$ PYTHONPATH=/workspaces/pipdeptree/temp-site-pkgs/ pipdeptree -a -d 0
Warning!!! Duplicate package metadata found:
"/home/vscode/.local/lib/python3.9/site-packages"
pluggy                           1.4.0            (using 1.4.0, "/workspaces/pipdeptree/temp-site-pkgs")
packaging                        24.0             (using 24.0, "/workspaces/pipdeptree/temp-site-pkgs")
tomli                            2.0.1            (using 2.0.1, "/workspaces/pipdeptree/temp-site-pkgs")
pytest                           8.1.1            (using 8.1.1, "/workspaces/pipdeptree/temp-site-pkgs")
exceptiongroup                   1.2.0            (using 1.2.0, "/workspaces/pipdeptree/temp-site-pkgs")
iniconfig …
```

Handle duplicated package metadata when using importlib.metadata

---

src/pipdeptree/_models/dag.py
src/pipdeptree/_models/package.py
tests/_models/test_dag.py
tests/_models/test_package.py
tests/conftest.py

Resolves #344.
This change also:
- Makes `Distribution.requires()` into a generator for performance (i.e. avoid building `list[Requirement]` and then iterating `list[Requirement` and instead do both at the same time) and so that we can handle invalid requirement exceptions in `PackageDAG.from_pkgs()` for each individual requirement string
- Modified conftest to avoid adding a extra comma at the end and removed some older code

Handle invalid requirement strings when using importlib.metadata

---

tests/test_non_host.py

Should finally resolve #343.
Before 2.17.0, we weren't honoring `$PYTHONPATH` when it was passed to the custom interpreter (but were honoring it when not using a custom interpreter).
With the changes made in 2.17.0, we (unexpectedly) began to honor `$PYTHONPATH` when using `--python`. I believe this is fine since as I explained above we honored it when it was used without this option and because of this it makes sense to pass this env var to the custom interpreter child process instead of ignoring it. Maybe we should document this in the 2.17.0 release notes?
This adds a test and changes another to ensure that there aren't future hiccups when using this env var.

Modify tests to ensure $PYTHONPATH is given to the custom interpreter

---

pyproject.toml
tests/test_pipdeptree.py

When we are using pytest in packaging process, we may not get the `/usr/bin/pipdeptree` as we need. So, let's use the `PATH` env to get the binary instead.
fix: https://github.com/tox-dev/pipdeptree/issues/348

Fix test_console failure finding pipdeptree in other environments

---

.github/ISSUE_TEMPLATE/0-new-issue.yml

Somehow missed the dropdown menu type when reading the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#dropdown) and to me this reads much better.
See an example by going to https://github.com/kemzeb/pipdeptree/issues and then navigate to `Report a Bug -> Get Started`.

Use dropdown instead of checkbox in bug report template

---

src/pipdeptree/__main__.py
src/pipdeptree/_cli.py
src/pipdeptree/_discovery.py
src/pipdeptree/_models/dag.py
src/pipdeptree/_validate.py
src/pipdeptree/_warning.py
tests/test_cli.py
tests/test_discovery.py
tests/test_validate.py
tests/test_warning.py

This resolves #355 by making changes and refactors to the warning logic. It does so by introducing a module-level singleton "WarningPrinter" object and refactors the code in such a way to integrate this object for it to be used.

Have duplicate metadata and invalid req strings honor --warn option

---

.github/workflows/check.yml

This appears to be a job that existed before we began publishing new releases using PyPI's [trusted publisher feature](https://docs.pypi.org/trusted-publishers/using-a-publisher/) in release.yml.
From exploring the Actions/Deployments tab, I could not find an instance where this job was ran. Seeing the `check` workflow configuration, we ignore all tag push events because of the `tags-ignore` usage. This would mean that `publish` will always be skipped since we don't listen for tag pushes in the `check` workflow. We also no longer have a `pypi_password` secret so even if it were to run it should fail.
I also decided to just remove the `tags-ignore` as according to the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-igno …

Remove publish job from the check workflow

---

src/pipdeptree/_discovery.py
tests/conftest.py
tests/test_discovery.py
tests/test_non_host.py

In v2.16.1, we would not print any user-site packages if we were:
- In a virtual environment
- Using a custom interpreter
This makes since as we should be isolated away from the system environment. The only case where we should be seeing user-site packages is when these environments have system site packages enabled. This patch brings back this behavior.

Mimic pip when handling --user-only in a virtual environment

---

README.md
src/pipdeptree/__main__.py
src/pipdeptree/_adapter.py
src/pipdeptree/_cli.py
src/pipdeptree/_detect_env.py
tests/test_detect_env.py

Implement --python auto for environment detection

---

src/pipdeptree/_discovery.py
tests/conftest.py
tests/test_discovery.py

Resolves #370.
I also decided to break away the "filtering" logic we have in `get_installed_distributions()` into its own function.

Warn about and ignore invalid package metadata in the environment

---

tests/test_pipdeptree.py

This removes a deprecation warning message that appears when running the automated tests.

Use non-deprecated pytest-console-scripts API

---

src/pipdeptree/_discovery.py

We don't actually depend on the backport, but a pytest plugin that we are using, pytest-console-scripts, does.
importlib_metadata==8.0.0 now raises a KeyError when we try to get metadata that doesn't exist (where before it would return None).
When running the automated tests, we would fail because the backport would for some reason take precedence over the stdlib. To resolve this, the current impl is replaced with a __contains__() call.

Use `__contains__` to avoid `KeyError` with importlib_metadata==8.0.0

---

src/pipdeptree/_models/package.py

Just a small refactor in ReqPackage to keep things DRY.

Use is_missing property in ReqPackage.is_conflicting() for DRYness

---

src/pipdeptree/_detect_env.py

Whoops, not sure why the pre-commit bot decided to remove this ignore rule in the first place.

Readd `# noqa: S603` to _detect_env to resolve Ruff error

---

src/pipdeptree/_models/package.py
tests/_models/test_package.py

Resolves #393.
This patch also removes unnecessary magic mock values from test_package.py.

Allow pre-releases when detecting version conflicts

---

src/pipdeptree/_freeze.py
src/pipdeptree/_models/package.py
tests/_models/test_package.py
tests/test_freeze.py

This snapshot moves the remaining pip API usage into the `freeze` module since we only use it to render dependency trees in the requirements.txt file format.
It also makes changes to related tests to make them true unit tests and creates an integration test for dist_to_frozen_repr().

Move pip's frozen requirement API into a single module

---

README.md
src/pipdeptree/__main__.py
src/pipdeptree/_cli.py
src/pipdeptree/_discovery.py
tests/test_cli.py
tests/test_discovery.py

Implement --path argument

---

.gitignore

This is a relic from an older test design that we no longer follow.

Remove unused .gitignore rule

---

src/pipdeptree/_cli.py
src/pipdeptree/_render/__init__.py

This also renames the argparse arg "encoding_type" to "encoding" to match what we have in the `Options` class.

Remove unnecessary assertion in render()

---

src/pipdeptree/_render/__init__.py
src/pipdeptree/_render/freeze.py
src/pipdeptree/_render/text.py
tests/render/test_freeze.py
tests/render/test_render.py
tests/render/test_text.py

This snapshot also adds tests for the freeze output (since they did not exist before). This refactor is done because of the following:
- The freeze output is not bound to change
- The text output is bound to change. This has been evident with features like unicode support, license metadata, and future support for more metadata and listing the deps of explicit extras. Having to ensure that freeze is still working as expected after such changes makes it harder to maintain
Though there is some code that is similar to the text output implementation, splitting this up will ensure that changes to the text output implementation won't cause problems to the freeze output implementation.

Split freeze and text output into their own implementations

---

src/pipdeptree/_render/graphviz.py

We currently expect graphviz>=0.20.3, so the try-except branch that was removed in this snapshot shouldn't ever execute.

Remove unused graphviz library code

---

src/pipdeptree/_models/package.py
tests/_models/test_package.py

Allows to display a license for projects with a new License-Expression field. For example, pipdeptree itself.
https://peps.python.org/pep-0639/#add-license-expression-field

Support for License-Expression field

---

tests/_models/test_package.py

Using Mock objects makes the intent more clearer compared to how we were using lambdas.

Refactor license option tests to use Mock objects instead of lambdas

---

src/pipdeptree/__main__.py
src/pipdeptree/_discovery.py
tests/test_discovery.py

Before we would just crash if given an invalid interpreter.
This change also does some code refactoring.

Handle exceptions when passed an invalid interpreter

---

pyproject.toml
tests/test_discovery.py
tests/test_pipdeptree.py

Resolves #474.
Due to us using the stdlib `importlib.metadata` and `pytest-console-scripts` using the backport version for Python versions < 3.10, this has caused some problems when `importlib_metadata` upgrades to a version that makes changes which is incompatible with the stdlib version.
After analyzing this plugin and the stdlib version of `importlib.metadata`, I ultimately decided to remove this plugin in favor of using `Distribution.entry_points()` to get the console script.

Replace `pytest-console-scripts` plugin with smaller in-house solution

---

pyproject.toml
tests/test_discovery.py
tests/test_non_host.py

virtualenv, as of v20.31.0, is no longer bundled with wheels. This change reflects this in tests that rely on knowing what packages are provided by default in a virtualenv environment.

Remove `wheel` package from tests due to virtualenv v20.31.0

---

src/pipdeptree/__main__.py
src/pipdeptree/_cli.py
src/pipdeptree/_models/dag.py
tests/_models/test_dag.py
tests/test_cli.py
tests/test_pipdeptree.py

#273 removed the ability to use --include and --exclude together. I now disagree with this change since not only was that a (accidental) breaking change but I now see it makes sense to allow them to be used together (e.g using pattern matching: `pidpeptree -p pytest* -e pytest-mock`).
This change allows them to be used together and adds a few tests to ensure that they continue to do so.

Allow --exclude to be used with --include

---

pyproject.toml
src/pipdeptree/_render/__init__.py
src/pipdeptree/_render/json.py
src/pipdeptree/_render/json_tree.py
src/pipdeptree/_render/mermaid.py
tests/render/test_json.py
tests/render/test_json_tree.py
tests/render/test_mermaid.py

It makes more sense to call print() inside the render functions because that’s their purpose. Some were already doing this anyways.
This change also adds a coverage test for the --json render.

Have render functions call print() themselves rather than the caller
